config/routes.rb
CmsAbus2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


    #путь к главной странице
    root :to => 'sessions#new'
    
    get "main/show" # Для второго меню

    
    #пути к ресурсам контроллеров      
    resources :main
    resources :cars do
      collection { post :update_domain, :destroy_domain, :sort }
    end 
    resources :images do
      collection { post :upload_image, :sort }
    end 
    resources :pages
    resources :domains
      match '/newdomain',  :to => 'domains#new'
    
    resources :users
      match '/registration',  :to => 'users#new'


    resources :sessions, :only => [:new, :create, :destroy]    
      match '/signup',  :to => 'users#new'
      match '/signin',  :to => 'sessions#new'
      match '/signout', :to => 'sessions#destroy'
      
   namespace :ckeditor do
      resources :pictures, :only => [:index, :create, :destroy]
      resources :attachment_files, :only => [:index, :create, :destroy]
      resources :attachments, :only => [:index, :create, :destroy]
    end
    
    
    match "/vehicle/:alias", :to => 'cars#show', :as => 'vehicle' # псевдоним для машин, дабы отображать по seo- user- friendly url

    
end

app/models/car.rb
class Car < ActiveRecord::Base
  
  has_many :images, :dependent => :delete_all
  has_many :cars_domains, :dependent => :delete_all
  has_many :domains, :through => :cars_domains
  
  attr_accessible :name, :short, :long, :is_show, :is_special, :title, :metadescription, :metakeywords,
  :alias, :price_hour, :price_MKAD, :min_zakaz, :transfer_sheremetevo,
  :transfer_vnukovo, :transfer_domodedovo, :transfer_ostafevo, :transfer_bikovo, :transfer_airport_airport, 
  :transfer_airport_station, :transfer_station_airport, :weeding_price_hour, :weeding_price_MKAD, 
  :weeding_min_zakaz, :weeding_friday, :weeding_saturday, :weeding_decor,
  :holiday, :holiday_min_zakaz, :holiday_weeding_min_zakaz
      
  validates :name, :presence => true
  validates :alias, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :is_show, :inclusion => {:in => [true, false]}
  
  def self.delete_car_full(car, car_images)
    
    car_images.each do |ci|
      FileUtils.rm_rf("#{RAILS_CAR_IMAGES}" + "#{ci.name}")
    end
    
    Car.find(car.id).destroy
  end
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:domain_id]
      @domain = Domain.find(params[:domain_id])
      @cars_domain = @domain.cars.order("order_id")
      @cars = Car.order('updated_at DESC').find(:all, :conditions => ['id not in(select car_id from cars_domains where domain_id = ?)', params[:domain_id]])
    else
       @cars = Car.order('updated_at DESC').all
    end   
    
    @domains = Domain.all
  end

  def show
    if params[:alias] != nil
      @car = Car.find(:first, :conditions => ["alias = ?", params[:alias]])
    else
      @car = Car.find(params[:id])
    end
      @image = @car.images.order("order_id").first
  end
  
  
  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params[:car])
    
    if @car.save
      flash[:success] = t('activerecord.errors.controllers.message.attributes.car.car_create_success')
       redirect_to cars_path
    else
      render 'new'
    end    
  end
  
  def update
    @car = Car.find(params[:id])
    
    if @car.update_attributes(params[:car])
      flash[:success] = t('activerecord.errors.controllers.message.attributes.car.car_update_success')
      redirect_to @car
    else
      redirect_to cars_path
    end
  end
  
  def destroy    
    car = Car.find(params[:id])
    car_images = car.images
    
    Car.delete_car_full(car, car_images)
    #Car.find(params[:id]).destroy
    
    flash[:success] = t('activerecord.errors.controllers.message.attributes.car.car_destroy_success')
    redirect_to cars_path
  end
  
  def update_domain
    cardomain = CarsDomain.new(:car_id => params[:car_id], :domain_id => params[:domain_id])
    cardomain.save
    
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def destroy_domain
    CarsDomain.where(:car_id => params[:car_id], :domain_id => params[:domain_id]).destroy_all

    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def sort
    params[:car].each_with_index do |id, index|
      CarsDomain.where(:domain_id => params[:domain_id]).update_all({order_id: index+1}, {car_id: id})
    end  
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_domains.html.erb
<% @domains.each do |domain| %>
	<%= content_tag_for :li, domain, :class => 'li-domain-car' do %>
	  <% if domain == @domain %>
		<span class='li-domain-selected'><%= domain.name %></span>
	  <% else %>
	    <%= link_to domain.name, cars_path(:domain_id => domain.id), :remote => true %>
	  <% end %>
	<% end %>
<% end %>

app/views/cars/_fields.html.erb
  <%= render 'layouts/error_page_messages', :object => f.object %>

  <div class="div-field">
    <%= f.label :name, t('field.car_name') %><br />
    <%= f.text_field :name, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :alias, t('field.car_alias') %><br />
    <%= f.text_field :alias, :class => "text-field" %>
  </div>

  <div class="div-field">
    <%= f.label :title, t('field.page_title') %><br />
    <%= f.text_field :title, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :metakeywords, t('field.page_meta_keywords') %><br />
    <%= f.text_field :metakeywords, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :metadescription, t('field.page_meta_description') %><br />
    <%= f.text_field :metadescription, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :short, t('field.car_short') %><br />
    <%= f.cktext_area :short, :class => "textarea-head" %>
  </div>  

  <div class="div-field">
    <%= f.label :long, t('field.car_long') %><br />
    <%= f.cktext_area :long, :class => "textarea-head" %>
  </div> 
  
  
<table cellpadding="0" cellspacing="0" width="100%">
 <tr><td class="td-field-price">
  
  <div class="div-field">
    <%= f.label :price_hour, t('field.car_price_hour') %><br />
    <%= f.text_field :price_hour, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :price_MKAD, t('field.car_price_MKAD') %><br />
    <%= f.text_field :price_MKAD, :class => "text-field" %>
  </div>

  <div class="div-field">
    <%= f.label :min_zakaz, t('field.car_min_zakaz') %><br />
    <%= f.text_field :min_zakaz, :class => "text-field" %>
  </div>  
    
 </td><td class="td-field-price">   	
  
  <div class="div-field">
    <%= f.label :transfer_sheremetevo, t('field.car_transfer_sheremetevo') %><br />
    <%= f.text_field :transfer_sheremetevo, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :transfer_vnukovo, t('field.car_transfer_vnukovo') %><br />
    <%= f.text_field :transfer_vnukovo, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :transfer_domodedovo, t('field.car_transfer_domodedovo') %><br />
    <%= f.text_field :transfer_domodedovo, :class => "text-field" %>
  </div>

  <div class="div-field">
    <%= f.label :transfer_ostafevo, t('field.car_transfer_ostafevo') %><br />
    <%= f.text_field :transfer_ostafevo, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :transfer_bikovo, t('field.car_transfer_bikovo') %><br />
    <%= f.text_field :transfer_bikovo, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :transfer_airport_airport, t('field.car_transfer_airport_airport') %><br />
    <%= f.text_field :transfer_airport_airport, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :transfer_airport_station, t('field.car_transfer_airport_station') %><br />
    <%= f.text_field :transfer_airport_station, :class => "text-field" %>
  </div>

  <div class="div-field">
    <%= f.label :transfer_station_airport, t('field.car_transfer_station_airport') %><br />
    <%= f.text_field :transfer_station_airport, :class => "text-field" %>
  </div>  
  
 </td><td class="td-field-price">  
  
  
  <div class="div-field">
    <%= f.label :weeding_price_hour, t('field.car_weeding_price_hour') %><br />
    <%= f.text_field :weeding_price_hour, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :weeding_price_MKAD, t('field.car_weeding_price_MKAD') %><br />
    <%= f.text_field :weeding_price_MKAD, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :weeding_min_zakaz, t('field.car_weeding_min_zakaz') %><br />
    <%= f.text_field :weeding_min_zakaz, :class => "text-field" %>
  </div>

  <div class="div-field">
    <%= f.label :weeding_friday, t('field.car_weeding_friday') %><br />
    <%= f.text_field :weeding_friday, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :weeding_saturday, t('field.car_weeding_saturday') %><br />
    <%= f.text_field :weeding_saturday, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :weeding_decor, t('field.car_weeding_decor') %><br />
    <%= f.text_field :weeding_decor, :class => "text-field" %>
  </div>


 </td><td class="td-field-price">
 	

  <div class="div-field">
    <%= f.label :holiday, t('field.car_holiday') %><br />
    <%= f.text_field :holiday, :class => "text-field" %>
  </div>  
  
  <div class="div-field">
    <%= f.label :holiday_min_zakaz, t('field.car_holiday_min_zakaz') %><br />
    <%= f.text_field :holiday_min_zakaz, :class => "text-field" %>
  </div>
  
  <div class="div-field">
    <%= f.label :holiday_weeding_min_zakaz, t('field.car_holiday_weeding_min_zakaz') %><br />
    <%= f.text_field :holiday_weeding_min_zakaz, :class => "text-field" %>
  </div>
  
  </td>
 </tr>
</table>

  <div class="div-field">
    <%= f.check_box :is_special, :class => "checkbox-field" %> <%= f.label :is_show, t('field.car_is_show_special') %>    
  </div>
  <div class="div-field">
    <%= f.check_box :is_show, :class => "checkbox-field" %> <%= f.label :is_show, t('field.car_is_show') %>    
  </div>

app/views/cars/_list.html.erb
<h4><%= t('views.car.car_remove_notice_header') %></h4>
<div class="div-move-car"><%= t('views.car.car_remove_notice') %></div>
<ul id="ul_cars" class="ul-cars-connectedSortable" data-update-url="<%= destroy_domain_cars_url %>">    
  <% @cars.each do |car| %>
	<%= content_tag_for :li, car, :class => 'li-car' do %>
		<%= link_to car.name, vehicle_path(:alias => car.alias) %> 
		(<%= link_to image_tag("buttons/edit.png", :alt => "#{t('views.buttons.edit')} #{car.name}", :title => "#{t('views.buttons.edit')} #{car.name}", :class => 'img-buttons'), car %>) 
    		<%= link_to image_tag("buttons/delete.png", :alt => "#{t('views.buttons.delete')} #{car.name}", :title => "#{t('views.buttons.delete')} #{car.name}", :class => 'img-buttons'), car, :method => :delete, :confirm => t('views.forms.confirm') %>
  	<div class="div-image"><%= link_to image_tag(car.images.order('order_id').first.image.url(:small)), car if car.images.order('order_id').first %></div>
  	<% end %>
  <% end %>
</ul>

app/views/cars/_list_selected.html.erb
<h4><%= t('views.car.car_add_notice_header') %></h4>
<div id="drop_car" class="div-move-car"><%= t('views.car.car_add_notice') %></div>
<% if @cars_domain %>
<ul id="ul_cars_selected" data-domain-id="<%= @domain.id if @domain %>" class="ul-cars-connectedSortable" data-update-url="<%= update_domain_cars_url %>" data-sortable-update-url="<%= sort_cars_url %>">  
       <% @cars_domain.each do |car| %>
         <%= content_tag_for :li, car, :class => 'li-car-domain' do %>
           <%= link_to car.name, vehicle_path(:alias => car.alias) %> 
           (<%= link_to image_tag("buttons/edit.png", :alt => "#{t('views.buttons.edit')} #{car.name}", :title => "#{t('views.buttons.edit')} #{car.name}", :class => 'img-buttons'), car %>) 
           		<%= link_to image_tag("buttons/delete.png", :alt => "#{t('views.buttons.delete')} #{car.name}", :title => "#{t('views.buttons.delete')} #{car.name}", :class => 'img-buttons'), car, :method => :delete, :confirm => t('views.forms.confirm') %>
            <div class="div-image"><%= link_to image_tag(car.images.order('order_id').first.image.url(:small)), car if car.images.order('order_id').first %></div>
          <% end %>
        <% end %>    
</ul>
<% else %>  
  <div><%= t('views.car.car_domain_empty') %></div>
<% end %>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/index.html.erb
<h1><%= t('views.car.welcome') %></h1>

<div id="domain_list">  
  <%= render 'domains'  %> 
</div>

<table width="500px">
<tr>
  <td width="50%">
  <div id="car_list">
  	<%= render 'list'  %>
  </div>
  </td>
  <td width="50%">
  <div id="car_list_selected">
    <%= render 'list_selected'  %> 
  </div>
  </td>
 </tr>
</table>

app/views/cars/index.js.erb
$('#domain_list').html("<%= escape_javascript(render('domains')) %>")
$('#car_list').html("<%= escape_javascript(render('list')) %>")
$('#car_list_selected').html("<%= escape_javascript(render('list_selected')) %>")

sortable_cars()

app/views/cars/new.html.erb
<h1><%= t('views.car.car_create_welcome') %></h1>


<%= form_for(@car) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="div-actions">
    <%= f.submit t('views.buttons.create') %>
  </div>
<% end %>

app/views/cars/show.html.erb
<h1><%= t('views.car.car_update_welcome') %></h1>
<br/>

<%= link_to image_tag(@image.image.url(:small)), :controller => 'images', :action => 'index', :car_id => @car.id if @image  %>


<%= link_to t('views.image.welcome'), :controller => 'images', :action => 'index', :car_id => @car.id %>

<%= form_for(@car) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="div-actions">
    <%= f.submit t('views.buttons.save') %>
  </div>
<% end %>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/cars/update_domain.js.erb
$('#car_list').html("<%= escape_javascript(render('list')) %>")
$('#car_list_selected').html("OK!")