config/routes.rb
CmsAbus2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


    #путь к главной странице
    root :to => 'sessions#new'
    
    get "main/show" # Для второго меню

    
    #пути к ресурсам контроллеров      
    resources :main
    resources :cars do
      collection { post :update_domain, :destroy_domain, :sort }
    end 
    resources :images do
      collection { post :upload_image, :sort }
    end 
    resources :pages
    resources :domains
      match '/newdomain',  :to => 'domains#new'
    
    resources :users
      match '/registration',  :to => 'users#new'


    resources :sessions, :only => [:new, :create, :destroy]    
      match '/signup',  :to => 'users#new'
      match '/signin',  :to => 'sessions#new'
      match '/signout', :to => 'sessions#destroy'
      
   namespace :ckeditor do
      resources :pictures, :only => [:index, :create, :destroy]
      resources :attachment_files, :only => [:index, :create, :destroy]
      resources :attachments, :only => [:index, :create, :destroy]
    end
    
    
    match "/vehicle/:alias", :to => 'cars#show', :as => 'vehicle' # псевдоним для машин, дабы отображать по seo- user- friendly url

    
end

app/views/layouts/_domain_menu.html.erb
<div class="header-domain-menu">
   	 <ul>   	 	
   	 	<li><%= link_to session[:current_domain_name], "http://"+session[:current_domain_name], :target => "_blank" %></li>
   	 	<li><%= link_to t('views.menu.mains'), :controller => 'main', :action=>'show' %></li>
   	 	<li><%= link_to t('views.menu.pages'), :controller => 'pages', :action=>'index' %> (<%= link_to t('views.menu.add'), new_page_path %>)</li>
   	 </ul>  
</div>

app/views/layouts/_error_domain_messages.html.erb
<% if object.errors.any? %>
  <div class="div-error-explanation">
    <h2><%= t('activerecord.errors.controllers.message.attributes.domain.domain_update_error')%> (<%= pluralize(object.errors.count, "error") %>)
        <br/><%= object.class.to_s.underscore.humanize.downcase %></h2>
        <br/>
    <p><%= t('activerecord.errors.controllers.message.attributes.domain.error_fields')%></p>
    <br/>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_page_messages.html.erb
<% if object.errors.any? %>
  <div class="div-error-explanation">
    <h2><%= t('activerecord.errors.controllers.message.attributes.page.page_update_error')%> (<%= pluralize(object.errors.count, "error") %>)
        <br/><%= object.class.to_s.underscore.humanize.downcase %></h2>
        <br/>
    <p><%= t('activerecord.errors.controllers.message.attributes.auth.error_fields')%></p>
    <br/>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_user_messages.html.erb
<% if object.errors.any? %>
  <div class="div-error-explanation">
    <h2><%= t('activerecord.errors.controllers.message.attributes.user.user_update_error')%> (<%= pluralize(object.errors.count, "error") %>)
        <br/><%= object.class.to_s.underscore.humanize.downcase %></h2>
        <br/>
    <p><%= t('activerecord.errors.controllers.message.attributes.auth.error_fields')%></p>
    <br/>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
	<% flash.each do |key, value| %>
          <div class="div-flash-<%= key %>"><%= value %></div>
	<% end %>

app/views/layouts/_header.html.erb
<header class="header-pages">
	<nav>
   	 <ul>
    	<% if signed_in? %>
   	 			<li><%= link_to t('views.menu.domains'), :controller => 'domains', :action=>'index' %> (<%= link_to t('views.menu.add'), new_domain_path %>)</li>
   	 			<li><%= link_to t('views.menu.cars'), :controller => 'cars', :action=>'index' %> (<%= link_to t('views.menu.add'), new_car_path %>)</li>
    			<li><%= link_to t('views.menu.users'), users_path %> (<%= link_to t('views.menu.add'), signup_path %>)</li>
    			<li><%= link_to current_user.name, edit_user_path(current_user) %> (<%= link_to t('views.menu.exit'), signout_path, :method => :delete %>)</li>
		<% end %>
   	 </ul>   
 	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsAbus2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>
</head>
<body>
<%= render 'layouts/header' %>

<div id="div_flash_box">
<%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>
</div>



<div class="div-content"><%= yield %></div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>